#### 问题场景

> 业务中使用到了`LRU`, 因`LRU`非线程安全, 故在进行`lru_cache.get()`和`lru_cache.put()`操作时使用了第三方库`python-redis-lock`进行加锁. 但在对业务`API`进行压测过程中, 出现如下异常:
>
> ```python
> Traceback (most recent call last):
> ......
> with redis_lock.Lock(redis_client=single_redis.redis, name=self.lock_key, expire=self.lock_expire):
> File "/lib/python3.6/site-packages/redis_lock/__init__.py", line 322, in __enter__
> 	acquired = self.acquire(blocking=True)
> File "/lib/python3.6/site-packages/redis_lock/__init__.py", line 211, in acquire
> 	if self._held:
> File "/lib/python3.6/site-packages/redis_lock/__init__.py", line 186, in _held
> 	return self.id == self.get_owner_id()
> File "/lib/python3.6/site-packages/redis_lock/__init__.py", line 200, in 		 get_owner_id
> 	return self._client.get(self._name)
> File "/lib/python3.6/site-packages/redis/client.py", line 976, in get
> 	return self.execute_command('GET', name)
> File "/lib/python3.6/site-packages/redis/client.py", line 668, in execute_command
> 	return self.parse_response(connection, command_name, **options)
> File "/lib/python3.6/site-packages/redis/client.py", line 680, in parse_response
> 	response = connection.read_response()
> File "/lib/python3.6/site-packages/redis/connection.py", line 624, in 		read_response
> 	response = self._parser.read_response()
> File "/lib/python3.6/site-packages/redis/connection.py", line 326, in read_response
> 	response = self.encoder.decode(response)
> File "/lib/python3.6/site-packages/redis/connection.py", line 125, in decode
> 	value = value.decode(self.encoding, self.encoding_errors)
> # 异常信息
> UnicodeDecodeError: 'utf-8' codec can't decode byte 0xcb in position 1: invalid continuation byte
> ```

#### 解决方案

> 经过对`python-redis-lock`库的版本更新记录查看, 发现3.3.0版本changelog如下:
>
> > ### 3.3.0 2019-01-17)
> >
> > - Fixed deprecated use of `warnings` API. Contributed by Julie MacDonell in [#54](https://github.com/ionelmc/python-redis-lock/pull/54).
> > - Added `auto_renewal` option in `RedisCache.lock` (the Django cache backend wrapper). Contributed by c in [#55](https://github.com/ionelmc/python-redis-lock/pull/55).
> > - Changed log level for “%(script)s not cached” from WARNING to INFO.
> > - Added support for using `decode_responses=True`. Lock keys are pure ascii now.
>
> 其中第四点即支持了`decode_responses=True`, 即可解决上述出现的问题.
>
> ```bash
> pip install python-redis-lock=3.3.0
> ```

#### 引用

> [python-redis-lock 3.3.0](https://pypi.org/project/python-redis-lock/3.3.0/)
>
> [redis 取gzip压缩过的数据UnicodeDecodeError的问题](https://my.oschina.net/pallormoon/blog/634712)
>
> [UnicodeDecodeError occurs when there is pickle binary data with decode_response=True](https://github.com/andymccurdy/redis-py/issues/809)
>
> [UnicodeDecodeError when decoding owner_id](https://github.com/ionelmc/python-redis-lock/issues/64)
>
> [Fails when use StrictRedis with decode_responses=True](https://github.com/ionelmc/python-redis-lock/issues/57)

